name: Build

on: [pull_request, push]

jobs:
  Archlinux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        dockerfile: Dockerfile-archlinux
        always_pull: true
        push: true
        cache_froms: ${{ github.repository }}/archlinux:latest
        repository: ${{ github.repository }}/archlinux
        tags: latest
        tag_with_ref: true
        tag_with_sha: true
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com

  Fedora:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        dockerfile: Dockerfile-fedora
        always_pull: true
        push: true
        cache_froms: ${{ github.repository }}/fedora:latest
        repository: ${{ github.repository }}/fedora
        tags: latest
        tag_with_ref: true
        tag_with_sha: true
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com

  OpenSUSE:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        dockerfile: Dockerfile-opensuse
        always_pull: true
        push: true
        cache_froms: ${{ github.repository }}/opensuse:latest
        repository: ${{ github.repository }}/opensuse
        tags: latest
        tag_with_ref: true
        tag_with_sha: true
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com

  Ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        dockerfile: Dockerfile-ubuntu
        always_pull: true
        push: true
        cache_froms: ${{ github.repository }}/ubuntu:latest
        repository: ${{ github.repository }}/ubuntu
        tags: latest
        tag_with_ref: true
        tag_with_sha: true
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
